name = "subtally"
main = "index.ts"
compatibility_date = "2026-05-14"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "subtally_db"

[[kv_namespaces]]
binding = "SESSIONS_KV"
preview_id = "sessions_kv_preview"
