/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUpcomingRouteImport } from './routes/dashboard.upcoming'
import { Route as DashboardServicesRouteImport } from './routes/dashboard.services'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUpcomingRoute = DashboardUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/upcoming': typeof DashboardUpcomingRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/upcoming': typeof DashboardUpcomingRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/upcoming': typeof DashboardUpcomingRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/signin'
    | '/dashboard/history'
    | '/dashboard/services'
    | '/dashboard/upcoming'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/signin'
    | '/dashboard/history'
    | '/dashboard/services'
    | '/dashboard/upcoming'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/settings'
    | '/signin'
    | '/dashboard/history'
    | '/dashboard/services'
    | '/dashboard/upcoming'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/upcoming': {
      id: '/dashboard/upcoming'
      path: '/upcoming'
      fullPath: '/dashboard/upcoming'
      preLoaderRoute: typeof DashboardUpcomingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardUpcomingRoute: typeof DashboardUpcomingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardUpcomingRoute: DashboardUpcomingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
